### ISSUE TITLE
Deploy succeeds but not displayed in deploy list

### ISSUE THREAD

**Issue by ekntrtmz** [pauloamgomes/CockpitCMS-Netlify#2]
First of all: THANK YOU FOR THIS GREAT ADDON!
I have a small issue with the deploy list though:
After successfully deploying from cockpit to netlify there will be no deploy shown in the list.

Cockpit Version: 0.9.2 (next branch)

**Comment by pauloamgomes** [comment]
Hi @ekntrtmz , not sure if understood the issue, the workflow should be:
1. Deploy is triggered
2. Addon is checking for deploy status an updates page, if finished it should displayed as published

I found recently that netlify sometimes takes too much time on the requests resulting in timed out, you can update the configurations to set the number of deploys to display in the page, that was added recently.

**Comment by ekntrtmz** [comment]
The issue was:

1. Deploy is triggered.
2. Deploy is built and published.
3. Deploy is listed in Netlify /deploys
4. Deploy is not listed in Cockpit /netlify/deploys 

The problem was that I had a wrong site-id in my cockpit/settings for Netlify plugin.
Do not use **Site Name**. Use **API ID** :)

**Comment by pauloamgomes** [comment]
Ok, so all good? can close the issue?
